### ISSUE TITLE
Administration.GameOptions' is obsolete: 'Use NwServer.ServerInfo.PlayOptions instead

### ISSUE THREAD

**Issue by milliorn** [nwn-dotnet/NWN.Managed#136]
I updated to **8193.20.43-dev.4**.  Console suggested this to me...
`Administration.GameOptions' is obsolete: 'Use NwServer.ServerInfo.PlayOptions instead.' [Services]`
[Link to code](https://github.com/milliorn/Eldritch-Warrior/blob/master/src/Services/Module/Load.cs)
So I changed...
`Administration.GameOptions.RestoreSpellUses = true;`
...to
`NwServer.Instance.ServerInfo.PlayOptions.RestoreSpellUses = true;`
When I launch I now get this error here
```
E [2021/02/23 04:51:02.904] [NWN.NManager] System.TypeLoadException: Could not load type 'NWN.API.NwServer' from assembly 'NWN.Managed, Version=8193.20.42.0, Culture=neutral, PublicKeyToken=null'.
   at Services.Module.Load.OnLoad(OnModuleLoad eventInfo)
   at NWN.API.Events.NativeEvent`2.InvokeCallbacks() in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/API/Events/Native/NativeEvent.cs:line 41
   at NWN.API.Events.NativeEvent`2.ProcessEvent() in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/API/Events/Native/NativeEvent.cs:line 35
   at NWN.API.Events.NativeEvent`2.NWN.API.Events.IEvent.Broadcast(NwObject objSelf) in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/API/Events/Native/NativeEvent.cs:line 27
   at NWN.Services.EventHandler.CallEvents(NwObject objSelf) in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/Services/Events/EventHandler.cs:line 42
   at NWN.Services.NativeEventService.NWN.Services.IScriptDispatcher.ExecuteScript(String scriptName, UInt32 oidSelf) in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/Services/Events/NativeEventService.cs:line 75
   at NWN.Services.DispatchServiceManager.OnRunScript(String script, UInt32 oidSelf) in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/Services/ScriptDispatch/DispatchServiceManager.cs:line 29
   at NWN.NManager.NWN.Core.IGameManager.OnRunScript(String script, UInt32 oidSelf) in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/NManager.cs:line 181 Could not load type 'NWN.API.NwServer' from assembly 'NWN.Managed, Version=8193.20.42.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by urothis** [comment]
https://github.com/milliorn/Eldritch-Warrior/pull/11
