### ISSUE TITLE
ExamineEvents: System.FormatException

### ISSUE THREAD

**Issue by Mefi100** [nwn-dotnet/NWN.Managed#49]
Recently encountered System.FormatException during ExamineEvents test. 

```csharp
using NWN.API;
using NWNX.API.Events;
using NWN.Services;

namespace KK2.Events.Examine 
{

  [ServiceBinding(typeof(ExamineBefore))]
  public class ExamineBefore
  {
    public ExamineBefore(EventService eventService)
    {
        eventService.SubscribeAll<ExamineEvents.OnExamineObjectBefore>(EventOnExamineBefore);
    }

    private void EventOnExamineBefore(ExamineEvents.OnExamineObjectBefore eventInfo)
    {
        NwPlayer pc = eventInfo.Examiner;
        NwObject obj = eventInfo.Examinee;

        pc.SendServerMessage($"Examined object: {obj.Name}");
    }
  }  
}
```

```
E [11:08:44] [NWNX_Events] [Events.cpp:160] Tried to access event data with invalid tag.
E [2020/11/06 11:08:44.761] [NWN.NManager] System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at NWN.API.StringExtensions.ParseInt(String intString)
   at NWN.API.StringExtensions.ParseIntBool(String intBoolString)
   at NWNX.API.Events.ExamineEvents.OnExamineObjectBefore.PrepareEvent(NwObject objSelf)
   at NWN.API.Events.Event.BroadcastEvent(NwObject objSelf)
   at NWN.Services.EventHandler.CallEvents(NwObject objSelf)
   at NWN.Services.EventService.NWN.Services.IScriptDispatcher.ExecuteScript(String scriptName, UInt32 oidSelf)
   at NWN.Services.DispatchServiceManager.OnRunScript(String script, UInt32 oidSelf)
   at NWN.NManager.NWN.Core.IGameManager.OnRunScript(String script, UInt32 oidSelf) Input string was not in a correct format.
```

**Comment by Mefi100** [comment]
This is resolved in 8193.16.33. Thanks!
